import { Poppins } from "next/font/google";
import "./globals.css";
import Toaster from "react-hot-toast";
import Head from "next/head";

const poppins = Poppins({
  weight: ["300", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
    <link rel="shortcut icon" href="/favicon.ico" />
    </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
